language: c
sudo: false
services:
  - docker
script:
  - bash ./tools/build-docker.sh
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a -n "$DOCKER_HUB_TAG" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag local-build xenserver/xs-opam:$DOCKER_HUB_TAG;
      docker push xenserver/xs-opam:$DOCKER_HUB_TAG;
    fi
env:
  global:
    - OCAML_VERSION=4.04.2
    - DISTRO=centos-7
  matrix:
    - BASE_REMOTE=/xs-opam DOCKER_HUB_TAG=latest
    - BASE_REMOTE=/xs-opam COMPILE_ALL=1 DOCKER_HUB_TAG=latest_extra
    - EXTRA_REMOTES=/xs-opam COMPILE_ALL=1
    - BASE_REMOTE=/xs-opam COMPILE_ALL=1 CHECK_UNUSED=1
    - BASE_REMOTE=/xs-opam OPAM_LINT=1
    - DISTRO=debian-stable BASE_REMOTE=/xs-opam COMPILE_ALL=1
    - OCAML_VERSION=4.05.0 EXTRA_REMOTES=/xs-opam COMPILE_ALL=1
matrix:
  fast_finish: true
  allow_failures:
    - env: BASE_REMOTE=/xs-opam OPAM_LINT=1
    - env: EXTRA_REMOTES=/xs-opam COMPILE_ALL=1
    - env: DISTRO=debian-stable BASE_REMOTE=/xs-opam COMPILE_ALL=1

