language: c
os: linux
dist: xenial
services:
  - docker
script:
  - bash tools/travis.sh
jobs:
  fast_finish: true
  include:
    - env: OPAMWITHTEST=false
    - env: OPAMWITHTEST=true
    - env: OPAMWITHTEST=true OCAML_VERSION=4.09
  allow_failures:
    - env: OPAMWITHTEST=true OCAML_VERSION=4.09
